Testing if environment will fail correctly

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,14 +7,14 @@
 # SSH_HOST_PRE
 # DB_CONNECTIONSTRING_STAGING
 
-name: Preproduction Deployment #shoutout to the exercises session
+name: Deploy #shoutout to the exercises session
 
 on:
   push:
     branches:
-      - develop
-      - main
-      - feature/156-change-workflow-to-a-single-file-+-environments
+      - 'feature/156-change-workflow-to-a-single-file-+-environments'
+      - 'develop'
+      - 'main'
   workflow_dispatch:
 
 jobs:
@@ -23,16 +23,21 @@ jobs:
     env:
       ENVIRONMENT: ${{ 
         github.ref == 'refs/heads/main' && 'production' ||
-        github.ref == 'refs/heads/staging' && 'staging' ||
-        github.ref == 'refs/heads/feature/156-change-workflow-to-a-single-file-+-environments' && 'staging' }}
-
+        github.ref == 'refs/heads/develop' && 'staging' ||
+        github.ref == 'refs/heads/feature/156-change-workflow-to-a-single-file-+-environments' && '' }}
 
     steps:
+      - name: Check environment
+        run: |
+          if [ -z "${ENVIRONMENT}" ]; then
+            echo "Environment could not be determined. Exiting."
+            exit 1
+          else
+            echo "Current environment is $ENVIRONMENT"
+          fi
+
       - name: Checkout
         uses: actions/checkout@v2
-
-      - name: Show environment
-        run: echo "Current environment is ${{ env.ENVIRONMENT }}."
 
 #       - name: Login to Docker Hub
 #         uses: docker/login-action@v1
