Another test

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -9,39 +9,22 @@ on:
     types: [opened, reopened, edited, synchronize, ready_for_review] 
 
 jobs:
-  build-image:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout repo
-          uses: actions/checkout@v4
-        
-        - name: Build Docker image
-          run: docker build -t csharp-minitwit:latest ./csharp-minitwit
-
-        - name: Wait 5 seconds
-          run: sleep 5
-
   run-tests:
-    needs: build-image
     runs-on: ubuntu-latest
-    services:
-      csharp-minitwit:
-        image: csharp-minitwit:latest
-        ports:
-          - 5000:5000
-        options: --detach
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Check Public Endpoint
-        run: |
-          response=$(curl -v http://localhost:5000/public)
-          echo "Response: $response"
+      - name: Wait for docker
+        run:
+            sleep 5
 
-      - name: Print Docker Logs
-        if: ${{ failure() }}
-        run: docker logs csharp-minitwit-container
+      - name: Build Docker image
+        run: docker build -t csharp-minitwit:latest ./csharp-minitwit
+
+      - name: Run Docker container
+        run: |
+          docker run -d --name csharp-minitwit -p 5000:8080 csharp-minitwit:latest
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -53,6 +36,17 @@ jobs:
           cd ./csharp-minitwit/Tests
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+
+      - name: Check Docker Logs
+        run: docker logs csharp-minitwit
+
+      - name: Check Public Endpoint
+        run: |
+          status_code=$(curl -v -s -o /dev/null -w "%{http_code}" http://localhost:5000/public)
+          if [ "$status_code" -ne 200 ]; then
+            echo "Error: Expected status code 200, but received $status_code"
+            exit 1
+          fi
 
       - name: Run Python tests
         run: |
