Check if application is up

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -37,6 +37,14 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+      - name: Check Public Endpoint
+        run: |
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/public)
+          if [ "$status_code" -ne 200 ]; then
+            echo "Error: Expected status code 200, but received $status_code"
+            exit 1
+          fi
+
       - name: Run Python tests
         run: |
           cd ./csharp-minitwit/Tests
